from .donation_views import *
from .verification_views import *
from .organisation_view import *
from .hospital_dashboard_view import *
from .user_views import *
from .donor_views import *
from .patient_views import *
from .password_reset_view import *
from .blood_request_view import *
from .inventory_views import *